line-length = 100
target-version = "py312"

[lint]
future-annotations = true
preview = true
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "ANN",
  "ASYNC",
  "S",
  "B",
  "A",
  "C4",
  "DTZ",
  "EM",
  "FA",
  "ISC",
  "LOG",
  "G",
  "PIE",
  "T20",
  "PT",
  "RSE",
  "RET",
  "SLOT",
  "SIM",
  "TC",
  "ARG",
  "PTH",
  "PL",
  "TRY",
  "FAST",
  "PERF",
  "FURB",
  "RUF",
]
ignore = [
  "assert",    # Assert used
  "magic-value-comparison", # Magic value used
  "ambiguous-unicode-character-comment",  # Comment contains ambiguous character
  "no-self-use", # Method could be a function, class method, or static method
  "any-type",  # typing.Any used
  "call-datetime-strptime-without-zone",  # Naive datetime constructed
  "line-too-long",    # Line too long
  "suspicious-non-cryptographic-random-usage",    # Standard pseudo-random generators are not suitable for security/cryptographic purposes

  "asyncio-dangling-task",
  "too-many-statements-in-try-clause",
]

[lint.per-file-ignores]
"**/__init__.py" = ["undefined-local-with-import-star", "unused-import"] # Wildcard imports used
"test.py" = ["ALL"]
"migrations/*.py" = ["ALL"]

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
  "pydantic.BaseModel",
  "pydantic_settings.BaseSettings",
]

[lint.mccabe]
max-complexity = 15

[lint.pydocstyle]
convention = "google"

[lint.isort]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
