name: Ruff lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'embed_fixer/**.py'
      - 'run.py'
      - 'ruff.toml'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ruff-lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'embed_fixer/**.py'
      - 'run.py'
      - 'ruff.toml'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ruff-lint.yml'

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ruff lint
        uses: astral-sh/ruff-action@v3