name: Update README

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ci.py
      - embed_fixer/fixes.py
      - embed_fixer/settings.py
      - .github/workflows/update_readme.yml

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --frozen --no-dev

      - name: Run CI script
        run: uv run ci.py

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: Update README" && git push)
